# 本番
baseURL = "https://a-sakagami.github.io/static_E2Esite/"
# ローカル確認用
# baseURL = "http://localhost:1313/static_E2Esite/"
languageCode = 'ja-jp'
title = '業務連絡フロー'
publishDir = 'public'

[permalinks]
posts = "/posts/:slug/"
