name: build hugo  # 任意の名前をつけます

on:
  push:
    branches:
      - master
  workflow_dispatch:  # 手動でワークフローをトリガーする設定

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true  # サブモジュールを取得する

    - name: Setup SSH for Deployment
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GENZPC1206 }}

    - name: Build and Deploy
      run: |
        echo "Deploying the project using SSH"   

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'

    - name: Build Hugo Site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages  # gh-pages ブランチにデプロイ
